# Generated by Django 2.2.9 on 2020-01-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20200122_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='phone_number',
            field=models.CharField(max_length=30),
        ),
    ]
