# Generated by Django 2.2.9 on 2020-02-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20200128_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=100)),
                ('method', models.IntegerField(verbose_name=2)),
                ('time_delta', models.DecimalField(decimal_places=3, max_digits=5)),
                ('user_id', models.IntegerField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
